import { Inter } from "next/font/google";
import "./globals.css";
import { Inter as FontSans } from "next/font/google"
import { PrimeReactProvider, PrimeReactContext } from 'primereact/api';

import { cn } from "@/lib/utils"

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <PrimeReactProvider value={{ unstyled: true }}>
      <html>
        <head />

        <body className={cn("min-h-screen bg-[#fbfbfb9e] font-sans antialiased", fontSans.className)}>

          <main className="">
            {children}
          </main>

        </body>
      </html>
    </PrimeReactProvider>
  );
}
